
CREATE TABLE EMPLOYEES 
(
EMP_ID INT,
NAME VARCHAR(10),
DEPT_ID INT,
SALARY INT,
CITY VARCHAR(10)
)

--INSERT INTO EMPLOYEES VALUES(1,'MAHESH',1,10000,'MELBORNE')
--INSERT INTO EMPLOYEES VALUES(2,'JANVI',2,200000,'RAJKOT')
--INSERT INTO EMPLOYEES VALUES(3,'RAMESH',3,25000,'AHMEDABAD')
--INSERT INTO EMPLOYEES VALUES(4,'VAMSI',4,15000,'BANGALURU')
--INSERT INTO EMPLOYEES VALUES(5,'KRISHNA',5,13000,'CHENNAI')
--INSERT INTO EMPLOYEES VALUES(6,'RAJESH',4,40000,'HYDERABAD')
--INSERT INTO EMPLOYEES VALUES(7,'MAHI',5,70000,'CHENNAI')
--INSERT INTO EMPLOYEES VALUES(8,'NIKHIL',3,80000,'MUMBAI')
--INSERT INTO EMPLOYEES VALUES(9,'KAJAL',8,12000,'PUNE')
--INSERT INTO EMPLOYEES VALUES(10,'POOJA',3,50000,'NOIDA')
--INSERT INTO EMPLOYEES VALUES(11,'SEEMA',2,30000,'DELHI')
--INSERT INTO EMPLOYEES VALUES(12,'NISHA',1,66000,'CHENNAI')

CREATE TABLE DEPARTMENT
(
ID INT,
DEPT_NAME VARCHAR(10)
)

--INSERT INTO DEPARTMENT VALUES(1,'HR')
--INSERT INTO DEPARTMENT VALUES(2,'IT')
--INSERT INTO DEPARTMENT VALUES(3,'ACCOUNT')
--INSERT INTO DEPARTMENT VALUES(4,'INOFFICE')
--INSERT INTO DEPARTMENT VALUES(9,'JAVA')
--INSERT INTO DEPARTMENT VALUES(10,'.NET')

SELECT * FROM EMPLOYEES

SELECT * FROM DEPARTMENT

SELECT * FROM EMPLOYEES 
CROSS JOIN DEPARTMENT 



-------------------INNER JOIN
SELECT * FROM EMPLOYEES E 
INNER JOIN DEPARTMENT D ON E.DEPT_ID = D.ID

-----------------LEFT JOIN
SELECT * FROM EMPLOYEES E 
LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.ID


----------------LEFT ANTI JOIN
SELECT * FROM EMPLOYEES E 
LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.ID
WHERE D.ID IS  NULL

--------------------RIGHT JOIN
SELECT * FROM EMPLOYEES E 
RIGHT JOIN DEPARTMENT D ON E.DEPT_ID = D.ID

------------RIGHT ANTI JOIN
SELECT * FROM EMPLOYEES AS E-----------ALIAS 
RIGHT JOIN DEPARTMENT AS D ON E.DEPT_ID = D.ID
WHERE E.DEPT_ID IS NULL

------------------FULL OUTER JOIN
SELECT * FROM EMPLOYEES E 
FULL JOIN DEPARTMENT D ON E.DEPT_ID = D.ID

SELECT * FROM EMPLOYEES E 
FULL JOIN DEPARTMENT D ON E.DEPT_ID = D.ID
WHERE 
(
E.DEPT_ID IS NULL OR D.ID IS NULL
)




-------------FULL ANTI JOIN
SELECT * FROM EMPLOYEES E 
FULL JOIN DEPARTMENT D ON E.DEPT_ID = D.ID
WHERE 
(
E.DEPT_ID IS NULL  OR
D.ID IS NULL
)

