SELECT * FROM EMP E1

SELECT * FROM EMP E2


----EXAMPLE SELF JOIN

SELECT E1.*,E2.EMP_NAME AS MANAGER_NAME FROM EMP E1 
INNER JOIN EMP E2 ON E1.MGR_ID = E2.EMP_ID

SELECT E1.EMP_ID,E1.EMP_NAME,E1.SALARY,E2.EMP_NAME,
ISNULL(E2.EMP_NAME,'SUPER MANAGER') AS MANAGER_NAME 
FROM EMP E1 
LEFT JOIN EMP E2 ON E1.MGR_ID = E2.EMP_ID

